spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CRUD?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: likelion
    password: likelion # ?? ????? ????? ???!

  jpa:
    hibernate:
      ddl-auto: create # ?? ????? ???? ??? ??
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.x ?? ?
        format_sql: true
